myapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('hakkimizda/', views.about, name='about'),
    path('faaliyetalanlarimiz/', views.services, name='services'),
    path('blog/', views.blog, name='blog'),
    path('iletisim/', views.contact, name='contact'),
    path('blog/<int:pk>/', views.post_detail, name='post_detail'),
    path('arama/', views.search, name='search_results'),
    path('basarili/', views.success, name='success'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from PIL import Image

import os

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    read_count = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Message(models.Model):
    from_email = models.EmailField(null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    subject = models.CharField(max_length=50, null=True, blank=True)
    message = models.TextField(blank=False, null=False)

    def __str__(self):
        return self.message[:20]

myapp/forms.py
from django import forms
from .models import Message

class SearchForm(forms.Form):
    q = forms.CharField( max_length=50)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('from_email', 'phone', 'subject', 'message',)

myapp/views.py
from django.shortcuts import render, redirect
from .models import Post
from .models import Message
from .forms import SearchForm
from .forms import ContactForm
from django.db.models import Q 

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def home_page(request):
    posts = Post.objects.order_by('-read_count')[:3]
    return render(request, 'myapp/home_page.html', {'articles': posts})

def about(request):
    return render(request, 'myapp/about.html')

def services(request):
    return render(request, 'myapp/services.html')

def blog(request):
    posts = Post.objects.all()
    form = SearchForm()
    return render(request, 'myapp/blog.html', {'articles': posts, 'form':form})

def search(request):
    query = request.GET.get('q')
    posts = Post.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
    form = SearchForm()
    return render(request, 'myapp/blog.html', {'articles': posts, 'form':form})


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    post.read_count += 1
    post.save()
    return render(request, 'myapp/post_detail.html', {'post':post})

def contact(request):
    if request.method == 'GET':
        form = ContactForm(data={'message':'Mesaj:'})
        form.fields['subject'].widget.attrs['label'] = 'message'

    else:
        print("else")
        form = ContactForm(request.POST)
        if form.is_valid():
            print("valid")
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            msg = form.save(commit=False)
            msg.save()
            return redirect('success')
    return render(request, "myapp/contact.html", {'form': form})

def success(request):
    return HttpResponse('Success! Thank you for your message.')

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}


{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/about.css' %}">
{% endblock %}

{% block content %}
    <div class="about">
        <h1>Kurucu Avukat - Av. Nagihan Çelik</h1>
        <div id="about-content">
            <div id="about-text">
                <p>
                    Av. Nagihan Çelik 1994 yılında İzmir’de doğmuştur.  Aslen Malatyalı olan Çelik, Çimentaş Anadolu lisesini ikincilikle bitirmesinin ardından Gazi Üniversitesi Hukuk Fakültesinde hukuk öğrenimi görmüştür. Hukuk öğrenimini tamamladıktan sonra İzmir’e dönmüş, avukatlık stajını İzmir Barosu bünyesinde tamamlamıştır. Staj esnasında Türkiye Barolar Birliği Bölgelerarası Kurgusal Duruşma Yarışmasında İzmir Barosu’nu temsil eden takımda asil üye olarak yer almış, İzmir Barosu’na Ege bölgesi birinciliğini getirmiştir. Çelik, başarılı bir staj döneminin sonunda avukatlık ruhsatını alıp halihazırdaki Çelik Avukatlık Bürosu’nu kurmuştur. İzmir Ticaret Odası bünyesinde Dış Ticaret Uzmanlığı eğitimi almıştır. Aynı zamanda uzlaştırmacı olan Çelik, inşaat hukuku, ticaret hukuku, şirketler hukuku ve ceza hukuku başta olmak üzere hukukun her alanında müvekkillerine danışmanlık ve dava takibi hizmetleri vermektedir.
                    
                </p>
                <p>
                    Çelik Avukatlık Bürosu,
                    <br>
   Müvekkillerine karşı şeffaf, her an ulaşılabilir, güvenilir ve çözüm odaklı hizmet verme anlayışını misyon; tek tek hayatına dokunduğu her insan ile insanlık huzur ve adaletine ulaşmayı vizyon edinmiş bir bürodur.
                </p>
            </div>
            <div>
    
            </div>
            <div id="about-img">
                <img src="{% static 'terazi.jpg' %}" alt="">
            </div>
        </div>
        
    </div>
{% endblock content %}

myapp/templates/myapp/base.html
{% load static %}
<html>
    <head>
        <title>ÇAB</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
      <nav>
        <div class="logo"><a href="{% url 'home_page' %}">ÇELİK</a></div>
        <div class="slogan">Avukatlık Bürosu</div>
        <div class="phone">
          <div class="phone-text">
            <i class="material-icons">call</i>
            <p>Bizi Arayın</p>
          </div>
          <p>+90 505 065 3067</p>
        </div>
        <div class="menu-items">
          <li>
            <a href="{% url 'home_page' %}">Anasayfa</a>
          </li>
          <li>
            <a href="{% url 'about' %}">Hakkımızda</a>
          </li>
          <li>
            <a href="{% url 'blog' %}">Blog</a>
          </li>
          <li id="last-menu-item">
            <a href="{% url 'contact' %}">İletişim</a>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
      <footer>
        <!--
        <div>
          <h4>Adres</h4>
          Adalet, 1586/7. Sk. No:10 D:203, 35540 Bayraklı/İzmir
        </div>
        <div>
          <h4>Telefon</h4>
          +90 505 065 3067
        </div>
        -->
        <div>
          <a href="https://www.linkedin.com/in/nagihan-%C3%A7elik-9b404b171/" class="fa fa-linkedin" target="_blank"></a>
          <a href="#" class="fa fa-instagram" target="_blank"></a>
        </div>
      </footer>
    </body>
</html>

myapp/templates/myapp/blog.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
    <div class="articles">
    <!--<h1 class="articles-heading">Yayınlar</h1>-->
    <div class="search">
        <form action="{% url 'search_results' %}" method="GET">
            <input id="search-input" name="q" type="text" placeholder="Bir yazı arayın">
        <button type="submit">
            <i class="material-icons">search</i>
        </button>
    </form>
    </div>
    {% for article in articles %}
      <div class="blog-article">
          <a href="{% url 'post_detail' pk=article.id %}">
              <img class="blog-article-image" src="{{article.image.url}}"></img>
          </a>
        <div class="blog-article-content">
          <p class="blog-article-date">{{ article.published_date|date:"d F Y" }}</p>
          <h1 class="blog-article-heading" ><a href="{% url 'post_detail' pk=article.id %}">{{ article.title }}</a></h1>
          <p class="blog-article-short-text">{{ article.text }}</p>
          <a class="continue-reading" href="{% url 'post_detail' pk=article.id %}" >Devamını Oku >></a>
        </div>
      </div>
    {% endfor %}
    </div>

{% endblock %}

myapp/templates/myapp/contact.html
{% extends 'myapp/base.html' %}
{% block content %}
    <div id="contact">
        <div>
            <div class="contact-item">
                <i class="material-icons">location_on</i>
                <p>Adalet, 1586/7. Sk. No:10 D:203, 35540 Bayraklı/İzmir</p>
            </div>
            <div class="contact-item">
                <i class="material-icons">local_phone</i>
                <p>+90 505 065 3067</p>
            </div>
            <div class="contact-item">
                <i class="material-icons">mail</i>
                <p>av.nagihancelik@gmail.com</p>
            </div>
        </div>

        <form id="contact-form" method="POST">
            <h1>Bize Ulaşın</h1>
            {% csrf_token %}
            <p>
                <p style="display: inline;" >E-posta</p>
                <input type="email" name="from_email" id="id_email" class="form-item">
            </p>
            <p>
                <p style="display: inline;" >Telefon</p>
                <input type="number" name="phone" id="id_phone" class="form-item">
            </p>
            <p>
                <p style="display: inline;" >Konu</p>
                <input type="text" name="subject" maxlength="50" id="id_subject" class="form-item">
            </p>
            <p>
                <p style="display: inline;" >Mesaj</p>
                <textarea form_id="contact-form" name="message" id="id_message" required class="form-item"></textarea>
            </p>
            <button type="submit" id="send-button">Gönder</button>
        </form>
    </div>
    
{% endblock %}

myapp/templates/myapp/home_page.html
{% extends 'myapp/base.html' %}

{% block content %}

    <div class="slidershow middle">

      <div class="slides">
        <input type="radio" name="r" id="r1" checked>
        <input type="radio" name="r" id="r2">
        <input type="radio" name="r" id="r3">
        <input type="radio" name="r" id="r4">
        <div class="slide s1">
          <div id="text1">
          </div>
        </div>
        <div class="slide s2">
          <div id="text2">
          </div>
        </div>
        <div class="slide s3">
          <div id="text3">
          </div>
        </div>
        <div class="slide s4">
          <div id="text4">
              <!--
              <h1 class="heading">Başlık</h1>
              <p class="header-paragraph">
                "Yazı"
              </p>
            -->
          </div>
        </div>
      </div>
  
      <div class="navigation">
        <label for="r1" class="bar"></label>
        <label for="r2" class="bar"></label>
        <label for="r3" class="bar"></label>
        <label for="r4" class="bar"></label>
      </div>
    </div>

    <section class="articles">
      <h1 class="articles-heading">Popüler Yayınlar</h1>
      {% for article in articles %}
        <div class="article">
          <div class="article-content">
            <p class="article-date">{{ article.published_date|date:"d F Y" }}</p>
            <h1>{{ article.title }}</h1>
            <p class="article-short-text">{{ article.text }}</p>
            <a class="continue-reading" href="{% url 'post_detail' pk=article.id %}" >Devamını Oku >></a>
          </div>
        </div>
      {% endfor %}
      <h2><a href="{% url 'blog' %}">Hepsini Gör</a></h2>
    </section>

{% endblock %}
<!--sources 
  Photo by Tyler Casey on Unsplash
  Photo by Kristijan Arsov on Unsplash
  Photo by Scott Graham on Unsplash
  Photo by Aron Yigin on Unsplash
  Photo by Mert Kahveci on Unsplash
  Photo by June O on Unsplash
  Photo by Jez Timms on Unsplash
  Photo by Giammarco Boscaro on Unsplash
  Photo by Patrick Fore on Unsplash
  Photo by Thomas Martinsen on Unsplash
  Photo by Augustine Wong on Unsplash
  Photo by Henry & Co. on Unsplash

-->

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<div id="post-detail">
    <h1>{{ post.title }}</h1>
    <p id="post-detail-date">{{post.published_date|date:"d F Y"}}</p>
    <img src="{{ post.image.url }}" alt="">
    <p>{{ post.text }}</p>
</div>

{% endblock %}

myapp/templates/myapp/search_results.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
    <div class="articles">
    <!--<h1 class="articles-heading">Yayınlar</h1>-->
    <div class="search">
        <form action="{% url 'search_results' %}" method="GET">
            <input id="search-input" name="q" type="text" placeholder="Search...">
        <button type="submit">
            <i class="material-icons">search</i>
        </button>
    </form>
    </div>
    {% for article in posts %}
      <div class="blog-article">
        <img class="blog-article-image" src="{% static 'img1.jpg' %}"></img>
        <div class="blog-article-content">
          <p class="blog-article-date">{{ article.published_date|date:"d F Y" }}</p>
          <h1>{{ article.title }}</h1>
          <p class="blog-article-short-text">{{ article.text }}</p>
          <a href="{% url 'article_full' pk=article.id %}" >Devamını Oku >></a>
        </div>
      </div>
    {% endfor %}
    </div>

{% endblock %}

myapp/templates/myapp/services.html
{% extends 'myapp/base.html' %}
{% block content %}
    <h1></h1>

{% endblock %}